layout: sidebar
style: dark

plugins:
  - jekyll-octicons

exclude:
  - default.conf
  - default.nix
  - CNAME
  - dev.Dockerfile
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - gemset.nix
  - LICENSE.txt
  - Makefile
  - node_modules
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - vendor
include:
  - .htacces
  - .htpasswd
  - .well-known

css_dir: assets/css
sass:
   sourcemap: never

url: "https://supersandro.de"
baseurl: ""
permalink: /:year/:month/:day/:title/

repository: supersandro2000/supersandro2000.github.io
email: sandro.jaeckel@posteo.de
pgp_key_id: "0x236b6291555e8401"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 11
  exclude:
    archived: true
    forks: true
    projects:
    - supersandro2000.github.io-old

thoughts:
  exclude:
    - "Privacy Policy"

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: "@sandro"
  # medium: your_username
  stackoverflow: 4446318
  steam: supersandro2000
  telegram: supersandro2000
  twitter: supersandro2000
  # unsplash: your_username
  # vk: your_username
  # website: https://supersandro.de/
  # youtube: supersand2000

topics:
  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png
  - name: Nix
    web_url: https://github.com/topics/nix
    image_url: https://raw.githubusercontent.com/NixOS/nixos-artwork/master/logo/nix-snowflake.svg
  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png
  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
  - name: Awesome Lists
    web_url: https://github.com/topics/awesome
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/awesome/awesome.png
  - name: Ruby
    web_url: https://github.com/topics/ruby
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ruby/ruby.png
  - name: Bash
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/bash/bash.png
  - name: Ubuntu
    web_url: https://github.com/topics/ubuntu
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ubuntu/ubuntu.png
